#cloud-config
  packages_update: true
  packages_upgrade: true

  packages:
    - ansible
    - git
    - openjdk-17-jdk  # Installation de Java
    - gnupg
    - software-properties-common
    - wget
    - maven
  runcmd:
    - apt-get update
    - apt-get install -y gnupg software-properties-common
# HashiCorp GPG key and source setup
    - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp.gpg
    - echo "deb [signed-by=/usr/share/keyrings/hashicorp.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    - sudo apt-get update
    - sudo apt-get install -y terraform

# Microsoft Azure CLI GPG key and source setup
    - sudo apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
    - sudo mkdir -p /etc/apt/keyrings
    - curl -sLS https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
    - sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
    - |
      AZ_DIST=$(lsb_release -cs) && echo "Types: deb
      URIs: https://packages.microsoft.com/repos/azure-cli/
      Suites: ${AZ_DIST}
      Components: main
      Architectures: $(dpkg --print-architecture)
      Signed-by: /etc/apt/keyrings/microsoft.gpg" | sudo tee /etc/apt/sources.list.d/azure-cli.sources
    - sudo apt-get update
    - sudo apt-get install -y azure-cli
    - apt-get update
    - apt-get install -y openjdk-17-jdk
    - apt-get install -y gnupg software-properties-common wget

    # Ajouter la clé et le dépôt de Jenkins
    - curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
    - echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
    - apt-get update

    # Installer Jenkins
    - apt-get install -y jenkins

    # Démarrer et activer Jenkins au démarrage
    - systemctl start jenkins
    - systemctl enable jenkins

    # Télécharger et installer la dernière version de Maven
    - wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz -P /tmp
    - tar xf /tmp/apache-maven-3.9.6-bin.tar.gz -C /opt
    - ln -s /opt/apache-maven-3.9.6 /opt/maven

    # Configurer les variables d'environnement pour Maven
    - echo "export M2_HOME=/opt/maven" >> /etc/profile.d/maven.sh
    - echo "export PATH=\$M2_HOME/bin:\$PATH" >> /etc/profile.d/maven.sh
    - chmod +x /etc/profile.d/maven.sh
    - source /etc/profile.d/maven.sh

    # Vérifier l'installation de Maven
    - mvn -version